// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-nYphsmJBeL2ymoB4oCRKgMgWhlTgdk',
    appId: '1:507175667352:web:cdd012292dbd792cc0b2ed',
    messagingSenderId: '507175667352',
    projectId: 'tonematch-protel',
    authDomain: 'tonematch-protel.firebaseapp.com',
    storageBucket: 'tonematch-protel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0BhVYiyScGQOBXm8R0sNW_mhReUOu3m4',
    appId: '1:507175667352:android:61124799ba680a3ec0b2ed',
    messagingSenderId: '507175667352',
    projectId: 'tonematch-protel',
    storageBucket: 'tonematch-protel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Rk4kYWA1jRH2UTbNUCGNxcj6YeU8SjU',
    appId: '1:507175667352:ios:3fac5d4fc0ff34a3c0b2ed',
    messagingSenderId: '507175667352',
    projectId: 'tonematch-protel',
    storageBucket: 'tonematch-protel.firebasestorage.app',
    iosBundleId: 'com.example.tonematch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Rk4kYWA1jRH2UTbNUCGNxcj6YeU8SjU',
    appId: '1:507175667352:ios:3fac5d4fc0ff34a3c0b2ed',
    messagingSenderId: '507175667352',
    projectId: 'tonematch-protel',
    storageBucket: 'tonematch-protel.firebasestorage.app',
    iosBundleId: 'com.example.tonematch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-nYphsmJBeL2ymoB4oCRKgMgWhlTgdk',
    appId: '1:507175667352:web:ea9e5ebe37cc8cdcc0b2ed',
    messagingSenderId: '507175667352',
    projectId: 'tonematch-protel',
    authDomain: 'tonematch-protel.firebaseapp.com',
    storageBucket: 'tonematch-protel.firebasestorage.app',
  );
}
